name: Hello CI

on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say hello and list files
        run: |
          echo "Hello from GitHub Actions!"
          echo "Repo: $GITHUB_REPOSITORY"
          ls -la
